### ISSUE TITLE
Implement endpoint to add a new Person

### ISSUE THREAD

**Issue by revangel** [revangel/nostalgiabot2#14]

**Comment by bellkelly** [comment]
Implement the API endpoint/service for creating a new Person in Nostalgiabot

### Acceptance Criteria

- [x] API accepts data of the form:

```json
POST /people
{
    "slack_user_id": "###",
    "first_name": "foo",
    "last_name": "bar",
}
```

- [x] A success returns a 201 response with the new user's serialized info.

- [x] `slack_user_id` should be unique to a user, so if a user with the same `slack_user_id` exists, raise a 409 conflict.
